---
version: '2'
services:
  zookeeper:
    image: docker.artifactory.tapsi.tech/confluentinc/cp-zookeeper:7.1.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: sn-zookeeper

  kafka:
    image: docker.artifactory.tapsi.tech/confluentinc/cp-kafka:7.1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    container_name: sn-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999

  kafka-jmx-exporter:
    image: docker.artifactory.tapsi.tech/danielqsj/kafka-exporter:latest
    ports:
      - "9308:9308"
    command: [ "--kafka.server=localhost:9092" ]
    depends_on:
      - kafka
    network_mode: host
  prometheus:
    image: docker.artifactory.tapsi.tech/prom/prometheus:latest
    network_mode: host
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
